// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace ImageOpt
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "image_lib.dll";



        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void compress_images_update_delegate(byte* arg1, long arg2);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void compress_images_process_start_delegate(int total);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void compress_images_warn_log_delegate(byte* arg1);

        [DllImport(__DllName, EntryPoint = "compress_images", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void compress_images(byte** paths, int len, [MarshalAs(UnmanagedType.U1)] bool zstd, [MarshalAs(UnmanagedType.U1)] bool overwrite, [MarshalAs(UnmanagedType.U1)] bool gen_mipmap, [MarshalAs(UnmanagedType.U1)] bool auto_scaling, int quality, compress_images_update_delegate update, compress_images_process_start_delegate process_start, compress_images_warn_log_delegate warn_log);

        [DllImport(__DllName, EntryPoint = "init_semaphore", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void init_semaphore(int limit);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void load_image_async_log_delegate(byte* arg1);

        [DllImport(__DllName, EntryPoint = "load_image_async", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void load_image_async(ushort* ptr, int len, [MarshalAs(UnmanagedType.U1)] bool enable_dds, load_image_async_log_delegate log, int tid);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void get_image_buffer_warn_log_delegate(byte* arg1);

        [DllImport(__DllName, EntryPoint = "get_image_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ImageBuffer get_image_buffer(int tid, get_image_buffer_warn_log_delegate warn_log);

        [DllImport(__DllName, EntryPoint = "load_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ImageBuffer load_image(ushort* ptr, int len, [MarshalAs(UnmanagedType.U1)] bool enable_dds);

        [DllImport(__DllName, EntryPoint = "free_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_buffer(ImageBuffer buffer);

        [DllImport(__DllName, EntryPoint = "free_string", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void free_string(byte* str);

        [DllImport(__DllName, EntryPoint = "get_expired", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern int get_expired();

        [DllImport(__DllName, EntryPoint = "set_auto_compress", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void set_auto_compress([MarshalAs(UnmanagedType.U1)] bool value);

        [DllImport(__DllName, EntryPoint = "get_device", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        [return: MarshalAs(UnmanagedType.U1)]
        internal static extern bool get_device(byte* ptr);

        [DllImport(__DllName, EntryPoint = "enqueue_image", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void enqueue_image(ushort* ptr, int len, int id);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void flush_log_log_delegate(byte* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void flush_log_warn_log_delegate(byte* arg1);

        [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
        internal delegate void flush_log_err_log_delegate(byte* arg1);

        [DllImport(__DllName, EntryPoint = "flush_log", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void flush_log(flush_log_log_delegate log, flush_log_warn_log_delegate warn_log, flush_log_err_log_delegate err_log);

        [DllImport(__DllName, EntryPoint = "wait_load_images", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern void wait_load_images();

        [DllImport(__DllName, EntryPoint = "get_texture", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ImageData get_texture(int id);

        [DllImport(__DllName, EntryPoint = "load_image_sync", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ImageData load_image_sync(ushort* ptr, int len);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ImageBuffer
    {
        public byte* ptr;
        public int length;
        public int width;
        public int height;
        [MarshalAs(UnmanagedType.U1)] public bool is_dds;
        public int mipmap_count;
        public UnityTextureFormat format;
        public nuint capacity;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct ImageData
    {
        public int width;
        public int height;
        public UnityTextureFormat format;
        public int mip_count;
        [MarshalAs(UnmanagedType.U1)] public bool is_dds;
        public int error;
        public byte* ptr;
    }


    internal enum UnityTextureFormat : byte
    {
        RGB24 = 3,
        RGBA32 = 4,
        ARGB32 = 5,
        RGB565 = 7,
        DXT1 = 10,
        DXT5 = 12,
        BGRA32 = 14,
        RHalf = 15,
        YUY2 = 21,
        BC6H = 24,
        BC7 = 25,
        BC4 = 26,
        BC5 = 27,
    }


}
